import { Instrument_Sans, Inter } from "next/font/google";
import "./_styles/globals.css";

const InstrumentSans = Instrument_Sans({
  subsets: ["latin"],
  display: "swap",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={InstrumentSans.className}>{children}</body>
    </html>
  );
}
